"""CourtMesh API Python SDK.

Example:
    from courtmesh import CourtMesh

    with CourtMesh(api_key="cm-...") as cm:
        result = cm.search_cases(query="right to privacy")
        for hit in result.data:
            print(hit.get("title"))
"""
from .client import CourtMesh, DEFAULT_BASE_URL
from .errors import (
    API_REFUSAL_CODES,
    ApiRefusalCode,
    AuthenticationError,
    BadGatewayError,
    CourtMeshError,
    InsufficientCreditsError,
    NotFoundError,
    PayloadTooLargeError,
    PermissionDeniedError,
    RateLimitError,
    RequestTimeoutError,
    ServerError,
    ServiceUnavailableError,
    ValidationError,
    build_error,
    is_retryable_429_code,
)
from .models import (
    APIResponse,
    AnalysisArguments,
    AnalysisIssue,
    AnalyzeResponse,
    CaseAnalysis,
    CaseAnalysisResponse,
    CaseDetails,
    CaseDetailsMetadata,
    CaseListItem,
    CitedCases,
    ConsolidatedAnalysis,
    ConsolidatedAnalyzeResponse,
    CoverageByCourtType,
    CoverageByYear,
    CoverageCourt,
    CoverageData,
    CoverageDistrictCourts,
    CoverageMeta,
    Envelope,
    HealthResponse,
    JudgeSearchMeta,
    Order,
    PartyRole,
    PartyScreenAddress,
    PartyScreenByBand,
    PartyScreenConfidence,
    PartyScreenCoverage,
    PartyScreenEvidence,
    PartyScreenIdentifiers,
    PartyScreenMatch,
    PartyScreenMeta,
    PartyScreenQueryEcho,
    PartyScreenRelatedMatch,
    PartyScreenResult,
    PartyScreenSignal,
    PartyScreenSummary,
    PdfResponse,
    RelatedDocument,
    RelatedResponse,
    RequestTimelineResponse,
    SearchCasesFilters,
    SearchCasesMeta,
    SearchCasesPagination,
    SearchCasesResult,
    SemanticSearchMeta,
    SemanticSearchPagination,
    SemanticSearchResult,
    SemanticSearchResultItem,
    TimelineEvent,
    TimelineJob,
)

__version__ = "0.3.0"

__all__ = [
    "CourtMesh",
    "DEFAULT_BASE_URL",
    "__version__",
    # errors
    "CourtMeshError",
    "ValidationError",
    "PayloadTooLargeError",
    "AuthenticationError",
    "InsufficientCreditsError",
    "PermissionDeniedError",
    "NotFoundError",
    "RequestTimeoutError",
    "RateLimitError",
    "ServerError",
    "BadGatewayError",
    "ServiceUnavailableError",
    "ApiRefusalCode",
    "API_REFUSAL_CODES",
    "is_retryable_429_code",
    "build_error",
    # models
    "APIResponse",
    "Envelope",
    "SearchCasesPagination",
    "SemanticSearchPagination",
    "SearchCasesResult",
    "SearchCasesMeta",
    "SearchCasesFilters",
    "SemanticSearchResult",
    "SemanticSearchMeta",
    "SemanticSearchResultItem",
    "CaseListItem",
    "CaseDetails",
    "CaseDetailsMetadata",
    "CaseAnalysis",
    "CaseAnalysisResponse",
    "AnalysisIssue",
    "CitedCases",
    "AnalysisArguments",
    "ConsolidatedAnalysis",
    "ConsolidatedAnalyzeResponse",
    "AnalyzeResponse",
    "RelatedDocument",
    "TimelineEvent",
    "RelatedResponse",
    "PdfResponse",
    "Order",
    "RequestTimelineResponse",
    "TimelineJob",
    "JudgeSearchMeta",
    "HealthResponse",
    "PartyRole",
    "PartyScreenIdentifiers",
    "PartyScreenAddress",
    "PartyScreenConfidence",
    "PartyScreenSignal",
    "PartyScreenEvidence",
    "PartyScreenMatch",
    "PartyScreenRelatedMatch",
    "PartyScreenByBand",
    "PartyScreenSummary",
    "PartyScreenCoverage",
    "PartyScreenQueryEcho",
    "PartyScreenResult",
    "PartyScreenMeta",
    "CoverageByCourtType",
    "CoverageByYear",
    "CoverageCourt",
    "CoverageDistrictCourts",
    "CoverageData",
    "CoverageMeta",
]
